## 错误处理
按照惯例，错误通常是最后一个返回值并且是 error 类型，一个内建的接口。
errors.New 构造一个使用给定的错误信息的基本error 值，返回错误值为 nil 代表没有错误。
通过实现 Error 方法来自定义 error 类型是可以的。

```go
package main

import (
	"errors"
	"fmt"
)

func f1(ary int) (int, error)  {
	if ary == 42 {
		return -1, errors.New("can't work with 42")
	}
	return ary +1, nil
}

type aryError struct {
	code int
	message string
}

func (e *aryError) Error() string {
	return fmt.Sprintf("%d - %s", e.code, e.message)
}
func f2(ary int) (int, error) {
	if ary == 42 {
		return -1, &aryError{ary, "can't work with 42"}
	}
	return ary +2, nil
}

func main() {
	for _, i := range []int{7, 42}{
		if r, e := f1(i); e != nil {
			fmt.Println("f1 failed", e)
		} else {
			fmt.Println("f1 work", r)
		}
	}

	for _, i := range []int{7, 42}{
		if r, e := f2(i); e != nil {
			fmt.Println("f2 failed", e)
		} else {
			fmt.Println("f2 work", r)
		}
	}
	_, e := f2(42)
	if ae, ok := e.(*aryError); ok {
		fmt.Println(ae.code)
		fmt.Println(ae.message)
	}
}

```